In [2]:
from prep_financial_phrasebank import clean_text
import nltk
import pandas as pd
import random
import numpy as np

nltk.download("stopwords")
nltk.download("wordnet")

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adlerviton/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/adlerviton/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [25]:
columns = ["sentence", "label"]
synthetic_df = pd.DataFrame(columns=columns)
for i in range(2000):
    max_length = 20
    length = int(np.round(np.random.uniform(0.15, 1) * max_length))
    types = 2
    sent = int(np.round(np.random.uniform(0, 1) * types))
    if sent == 1:
        rand_text = [
            random.choice(
                ("uh", "not", "up", "down", "maybe", "is", "less", "more", "same")
            )
            for _ in range(length)
        ]
    elif sent == 2:
        rand_text = [
            random.choice(
                ("good", "uh", "up", "maybe", "better", "is", "more", "great")
            )
            for _ in range(length)
        ]
    elif sent == 0:
        rand_text = [
            random.choice(
                ("bad", "uh", "down", "maybe", "worse", "is", "less", "terrible")
            )
            for _ in range(length)
        ]
    random_text = " ".join(rand_text)
    synthetic_df.loc[i] = [random_text, sent]  # Add rand_text to synthetic_df

synthetic_df

sentence  label
0     uh bad uh down uh uh is maybe bad bad uh bad i...      0
1            up good uh up great great is more up is up      2
2                          not up down less not less is      1
3     down maybe down maybe more is is maybe more up...      1
4       uh is up up maybe uh great great is uh up up is      2
...                                                 ...    ...
1995  good maybe maybe maybe uh up better up great g...      2
1996             less up not maybe maybe less less same      1
1997                                        is maybe is      2
1998  down maybe down maybe not up maybe uh up not n...      1
1999                                  is down more same      1

[2000 rows x 2 columns]

In [26]:
from prep_financial_phrasebank import (
    tokenize_financial_phrasebank,
    generate_data_word2vec,
)


def aggregate_fake_splits(fakedata):
    """
    Aggregate all splits of financial_phrasebank
    """
    df = fakedata
    df = tokenize_financial_phrasebank(df)
    X_train, y_train, X_test, y_test = generate_data_word2vec(df)
    return X_train, y_train, X_test, y_test

In [27]:
aggregate_fake_splits(synthetic_df)

(array([[-2.87146   , -1.0187988 ,  0.92822266, ...,  2.5339355 ,
         -1.142395  ,  4.5161133 ],
        [-8.705078  , -0.3168335 ,  1.310791  , ...,  2.758789  ,
         -4.491394  ,  9.781006  ],
        [-4.5458984 , -1.5222168 ,  1.439209  , ...,  2.3752441 ,
         -2.239746  ,  4.902832  ],
        ...,
        [-6.1606445 ,  2.1430664 , -0.5197754 , ...,  1.1033936 ,
         -2.443451  ,  8.682434  ],
        [-2.045288  , -0.01757812,  0.4958496 , ...,  1.0234375 ,
         -0.7989807 ,  2.8154297 ],
        [-4.5075073 , -0.35559082,  1.1030273 , ...,  2.5355225 ,
         -2.8240051 ,  5.9662476 ]], dtype=float32),
 array([1, 2, 1, ..., 0, 0, 1]),
 array([[ -4.713867  ,   1.0246582 ,   0.3881836 , ...,   2.0249023 ,
          -1.9231567 ,   7.689453  ],
        [ -5.4991455 ,  -0.07495117,   1.1713867 , ...,   2.3410645 ,
          -2.0603027 ,   7.3081055 ],
        [ -5.9834595 ,  -1.3416748 ,   0.9786377 , ...,   3.7557373 ,
          -2.6251526 ,   8.717651  ],
 

In [29]:
def run_experiment() -> None:
    from sklearn.linear_model import LogisticRegression

    # prepare training and testing data
    X_train, y_train, X_test, y_test = aggregate_fake_splits(synthetic_df)

    clf = LogisticRegression(random_state=0, max_iter=1000).fit(X_train, y_train)
    print("word2vec (train):", clf.score(X_train, y_train))
    print("word2vec (test):", clf.score(X_test, y_test))

    return clf

In [30]:
run_experiment()

word2vec (train): 0.9829545454545454
word2vec (test): 0.9823232323232324


LogisticRegression(max_iter=1000, random_state=0)