In [1]:
import prep_financial_phrasebank as prep
import nltk
import pandas as pd
from random_text import generate_observation
import numpy as np

[nltk_data] Downloading package gutenberg to
[nltk_data]     /Users/adlerviton/nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     /Users/adlerviton/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [4]:
nltk.download("stopwords")
nltk.download("wordnet")
google_news = prep.google_news
clf = prep.run_experiment()

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adlerviton/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/adlerviton/nltk_data...


word2vec (train): 0.6565434396413163
word2vec (test): 0.6362098138747885


/Users/adlerviton/miniconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [5]:
nltk.download("gutenberg")
nltk.download("punkt")
corpus = nltk.word_tokenize(nltk.corpus.gutenberg.raw("austen-sense.txt").lower())

[nltk_data] Downloading package gutenberg to
[nltk_data]     /Users/adlerviton/nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     /Users/adlerviton/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [6]:
columns = ["text", "vecs", "labels"]
synthetic_df = pd.DataFrame(columns=columns)
for i in range(50):
    rand_text = generate_observation(i, corpus)
    synthetic_df.loc[i] = [rand_text, None, None]  # Add rand_text to synthetic_df

synthetic_df["text"] = synthetic_df["text"].apply(prep.clean_text)
# remove empty strings
synthetic_df = synthetic_df[synthetic_df["text"] != ""]
# synthetic_df["vecs"] = synthetic_df["text"].apply(prep.send_to_vecs)

In [7]:
synthetic_df

text  vecs labels
0                       lucy smallest effect side two  None   None
1                              two miss steeles world  None   None
2   gracefulness instantly theme general civility ...  None   None
3                              two miss steeles world  None   None
4                                        direct world  None   None
5                              night sure said elinor  None   None
6                                                back  None   None
7                               good two miss steeles  None   None
8                              happy two miss steeles  None   None
9                           size smallest effect side  None   None
10                                              world  None   None
11                 dear said elinor sure would differ  None   None
12                             two miss steeles world  None   None
13                    appear advantage happy two miss  None   None
14                              park two miss steeles  None   None
15                urged matter sure would differ town  None   None
16                              good two miss steeles  None   None
17                                           offering  None   None
18                      said elinor sure would differ  None   None
19                    therefore sure said elinor sure  None   None
20                         sure would differ town two  None   None
21              fondly observed may glad see two miss  None   None
22                                             subdue  None   None
23                        sure said elinor sure would  None   None
24                 dear said elinor sure would differ  None   None
25                    entrance house two miss steeles  None   None
26       wisest touch point however sure would differ  None   None
27            sure would differ town two miss steeles  None   None
28          supported entrance house two miss steeles  None   None
29                imagination sister two miss steeles  None   None
30                      family two miss steeles world  None   None
31                      income two miss steeles world  None   None
32                       much sister two miss steeles  None   None
33            sure would differ town two miss steeles  None   None
34                             two miss steeles world  None   None
35                                   almost every day  None   None
36                                          went away  None   None
37                    marianne sure would differ town  None   None
38                         sure would differ town two  None   None
39                             house two miss steeles  None   None
40                              time two miss steeles  None   None
41                              sure said elinor sure  None   None
42                     look approbation inferior love  None   None
43                                   two miss steeles  None   None
45  satisfied affectionate principle mother two mi...  None   None
46                              time two miss steeles  None   None
47                 know said elinor sure would differ  None   None
48                   little together two miss steeles  None   None
49                        sure said elinor sure would  None   None

In [8]:
def generate_X_word2vec(df):
    X = np.array(
        [
            # sum the token embeddings for each sentence. If word is not in the model, return embedding of ['UNK']
            prep.sum_token_embeddings(
                [
                    google_news[word] if word in google_news else google_news["UNK"]
                    for _, word in enumerate(sentence)
                ]
            )
            for _, sentence in enumerate(df.text)
        ]
    )
    return X

In [9]:
X = generate_X_word2vec(synthetic_df)

In [10]:
clf.predict(X)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1])

In [26]:
rcf = prep.RandomForest_experiment()

word2vec (train): 0.854665425936892
word2vec (test): 0.7993231810490694


In [28]:
clf.predict(prep.generate_observation_word2vec("great earnings upbeat results"))

array([1], dtype=int64)

In [27]:
rcf.predict(X)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1], dtype=int64)

In [34]:
rcf.predict(
    prep.generate_observation_word2vec(
        "new production plant company would increase capacity meet expected increase demand would improve use raw materials therefore increase production profitability"
    )
)

array([1], dtype=int64)

In [37]:
gb = prep.GradientBoost_experiment()

word2vec (train): 0.8456983334743253
word2vec (test): 0.7928934010152284


In [38]:
gb.predict(X)

AttributeError: 'NoneType' object has no attribute 'predict'