In [35]:
import prep_financial_phrasebank as prep
import nltk
import pandas as pd
from random_text import generate_observation
import numpy as np

In [2]:
google_news = prep.google_news
clf = prep.run_experiment()

word2vec (train): 0.6490990609931477
word2vec (test): 0.6446700507614214


c:\Users\cerva\miniconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [6]:
nltk.download("gutenberg")
nltk.download("punkt")
corpus = nltk.word_tokenize(nltk.corpus.gutenberg.raw("austen-sense.txt").lower())

[nltk_data] Downloading package gutenberg to
[nltk_data]     C:\Users\cerva\AppData\Roaming\nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\cerva\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [7]:
columns = ["text", "vecs", "labels"]
synthetic_df = pd.DataFrame(columns=columns)
for i in range(50):
    rand_text = generate_observation(i, corpus)
    synthetic_df.loc[i] = [rand_text, None, None]  # Add rand_text to synthetic_df

synthetic_df["text"] = synthetic_df["text"].apply(prep.clean_text)
# remove empty strings
synthetic_df = synthetic_df[synthetic_df["text"] != ""]
# synthetic_df["vecs"] = synthetic_df["text"].apply(prep.send_to_vecs)

NameError: name 'clean_text' is not defined

In [24]:
def generate_X_word2vec(df):
    X = np.array(
            [
                # sum the token embeddings for each sentence. If word is not in the model, return embedding of ['UNK']
                prep.sum_token_embeddings(
                    [
                        google_news[word] if word in google_news else google_news["UNK"]
                        for _, word in enumerate(sentence)
                    ]
                )
                for _, sentence in enumerate(df.text)
            ]
        )
    return X

In [ ]:
X = generate_X_word2vec(synthetic_df)

In [25]:
clf = prep.run_experiment()
clf.predict(X)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1], dtype=int64)

In [26]:
rcf = prep.RandomForest_experiment()

word2vec (train): 0.854665425936892
word2vec (test): 0.7993231810490694


In [28]:
clf.predict(prep.generate_observation_word2vec('great earnings upbeat results'))

array([1], dtype=int64)

In [27]:
rcf.predict(X)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1], dtype=int64)

In [34]:
rcf.predict(prep.generate_observation_word2vec('new production plant company would increase capacity meet expected increase demand would improve use raw materials therefore increase production profitability'))

array([1], dtype=int64)

In [37]:
gb = prep.GradientBoost_experiment()

word2vec (train): 0.8456983334743253
word2vec (test): 0.7928934010152284


In [38]:
gb.predict(X)

AttributeError: 'NoneType' object has no attribute 'predict'